version: 2
updates:
  - package-ecosystem: 'github-actions'
    directories:
      - '/.github/actions/**/*'
      - '/.github/workflows/**/*'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'ci(github)'
