name: 'Parse .tool-versions'
description: 'Parse .tool-versions file, setting versions in env variables'
inputs:
  filename:
    description: ".tool-versions filename. default is `.tool-versions`"
    required: false
    default: '.tool-versions'
  uppercase:
    description: "should the variables be uppercase?"
    required: false
    default: "true"
  prefix:
    description: "prefix applied before the tool version name (eg. tool_version_)"
    required: false
  postfix:
    description: "postfix applied after the tool version name (eg. _tool_version)"
    required: false

branding:
  icon: list
  color: purple

runs:
  using: "composite"
  steps:
    - name: Retrieve version
      id: version
      shell: bash
      run: |
        env FILENAME=${{ inputs.filename }} UPPERCASE=${{ inputs.uppercase }} PREFIX=${{ inputs.prefix }} POSTFIX=${{ inputs.postfix }} bash ${GITHUB_ACTION_PATH}/parse_tool_versions.sh >> $GITHUB_ENV
