name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    permissions:
      contents: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Setup BATS
        uses: mig4/setup-bats@2859ea733ef81b6ba31008a7fba0cacfbf2a5429 # v1.2.0
        with:
          bats-version: 1.10.0

      - name: Run tests
        run: bats -r ./test/parse_tool_versions_test.bats
